
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Proyecto.Datos.Contexto.Repositorio;
//using Proyecto.Datos.Contexto.Repositorio;

namespace Proyecto.Datos.Contexto
{
    public partial class ContextoProyecto : DbContext
    {
        public ContextoProyecto()
        {
        }

        public ContextoProyecto(DbContextOptions<ContextoProyecto> options)
            : base(options)
        {
        }

        public virtual DbSet<Autores> Autores { get; set; }
        public virtual DbSet<Libros> Libros { get; set; }
        public virtual DbSet<LibrosAutores> LibrosAutores { get; set; } 
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Autores>(entity =>
            {
                entity.ToTable("Autores", "dbo");

                entity.HasKey(e => e.AutorID);
                entity.Property(e => e.AutorID).ValueGeneratedNever();
            });

            modelBuilder.Entity<Libros>(entity =>
            {
                entity.ToTable("Libros", "dbo");
                entity.HasKey(e => e.LibroID);
                entity.Property(e => e.LibroID).ValueGeneratedNever();
            });

            modelBuilder.Entity<LibrosAutores>(entity =>
            {
                entity.ToTable("LibrosAutores", "dbo");

                entity.HasKey(e => e.LibroAutorID);
                entity.Property(e => e.LibroAutorID).ValueGeneratedNever(); 
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
